import '../styles/globals.css'
import '../styles/style.scss'
import '../styles/profile.scss'
 
import NavBar from '../components/Router';
import styles from '../styles/Home.module.scss'
import Head from 'next/head'
import Image from 'next/image'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>ITKory</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="google" content="notranslate"/>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
         
      <NavBar></NavBar>
        
         

          <Component {...pageProps} />
        </main>
      </div>
    </>

  )
}

export default MyApp
