import '../styles/globals.css'
import '../styles/style.scss'
import '../styles/profile.scss'
import NavBar from '../components/Router';
import styles from '../styles/Home.module.scss'
import Head from 'next/head'
import Image from 'next/image'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>ITKory</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="google" content="notranslate"/>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
         
      <NavBar></NavBar>
        
         

          <Component {...pageProps} />
        </main>
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </>

  )
}

export default MyApp
